### PR TITLE
Change the retention policy of @ViewModelInject

### PR DESCRIPTION
**Pull request by gm-vm**

### CODE REVIEW

**Comment by gm-vm** [comment]
I honestly did not try this yet, I only noticed the warning while building a project using the library.

The alternative would be making the processor isolating, which means that we need to create a Dagger module for each ViewModel annotated with @ViewModelInject. However, unless we add an extra processor that takes all these modules to create a global module that includes them all (but I guess this can't be done incrementally), the user would have to include all the generated modules manually, which kind of defeats the purpose of this library.

If you are fine with this retention policy, this is probably the simplest solution.

**Comment by hansenji** [comment]
Please post more details on this warning. I am not seeing any using Gradle 5.6.1. Kotlin 1.3.50 and Android gradle plugin 3.6.0-beta01.

**Comment by gm-vm** [comment]
It's what I put in the commit message:
```
Created classpath snapshot for incremental compilation in 0.001 secs.
Class dependency analysis for incremental compilation took 0.008 secs.
Full recompilation is required because '@ViewModelInject' has source retention. Aggregating annotation processors require class or runtime retention. Analysis took 0.011 secs.
```

EDIT: Also mentioned here https://docs.gradle.org/current/userguide/java_plugin.html#aggregating_annotation_processors

**Comment by hansenji** [comment]
I pulled in your changes and extended it to all annotations in 6e211bb. 
Thanks

**Comment by gm-vm** [comment]
Right, I forgot about `@ViewModelModule`, that's what happens when you don't test your changes.

Anyway, I tried to split the processor: one is "isolating" and only looks for `ViewModel`s annotated with `@ViewModelInject` to generate the factories and related dagger modules, the other one is "aggregating" and looks for both `@ViewModelInject` and `@ViewModelModule` to generate the global module.

In theory such a setup would improve the performance given that changing one `ViewModel` will lead to the recompilation of just the changed `ViewModel` and the global module rather than the recompilation of all the annotated `ViewModel`s.

The problem is that I can't really test this, because incremental annotation processing appears to be broken. Using `0.3.2-rc01` without my changes I get the following:
```
project/path/some/package/App.java:6: error: cannot find symbol
import some.package.di.DaggerAppComponent;
                       ^
  symbol:   class DaggerAppComponent
  location: package some.package.di
project/path/some/package/di/AppComponent.java:40: error: [Dagger/MissingBinding] androidx.lifecycle.SavedStateHandle cannot be provided without an @Inject constructor or an @Provides-annotated method.
public interface AppComponent extends AndroidInjector<App> {
       ^
      javax.inject.Provider<androidx.lifecycle.SavedStateHandle> is injected at
          some.package.subpackage.MyViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage.MyViewModel_AssistedFactory is injected at
          some.package.di.ViewModelInject_AppViewModelModule.bind_some_package_subpackage_MyViewModel(factory)
      java.util.Map<java.lang.Class<?>,com.vikingsen.inject.viewmodel.AbstractViewModelFactory> is injected at
          com.vikingsen.inject.viewmodel.savedstate.SavedStateViewModelFactory.Factory(arg0)
      com.vikingsen.inject.viewmodel.savedstate.SavedStateViewModelFactory.Factory is injected at
          some.package.App.viewModelFactoryFactory
      some.package.App is injected at
          some.package.di.AppComponent.inject(some.package.App)
  It is also requested at:
      some.package.AViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage1.BViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage2.CViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage3.DViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage4.EViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage5.FViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage6.GViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage6.HViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage7.ViewModel_AssistedFactory(…, savedStateHandle)
      some.package.subpackage8.JViewModel_AssistedFactory(…, savedStateHandle)
      and 7 others
2 errors
```

Not sure where the problem is now.

EDIT: to make the output above a bit more clear. It's as if the `@Assisted` annotation is discarded, all the `*ViewModel_AssistedFactory` above should not have `savedStateHandle` as constructor parameter.

EDIT2: Oh, I see, `@Assisted` as SOURCE as retention. If I change that to CLASS, it kind of works. The problem I have now is that the name of the variables is lost on incremental builds and since there are some constraints on the name of assisted arguments, both in ViewModelInject and AssistedInject, the build fails.

**Pull request closed without merging**
